### ISSUE TITLE
Add and tweak world friction values

### ISSUE THREAD

**Issue by arunimaCh29** [HBRS-SDP/ss24-gazebo-simulation-freddy#17]
In the working setup no friction has been defined for the contact between wheels and the ground, and of the wheel joints. To have a realistic simulation, define the friction values for the above mentioned  components.

**Comment by ShinasShaji** [comment]
Fixed with [arunimaCh29/freddy_description `38c03ca`](https://github.com/arunimaCh29/freddy_description/commit/38c03ca8a62842a3ba2829cebb9c9cf5db13696d) and [HBRS-SDP/ss24-gazebo-simulation-freddy `7574522`](https://github.com/HBRS-SDP/ss24-gazebo-simulation-freddy/commit/757452234fa7b78dd4050943a904430c90830c55)
